name: e_commerce_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  db_client:
    path: packages/db_client

  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  uuid: ^4.2.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  go_router: ^13.1.0
  flutter_stripe: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
